CREATE TABLE DADOS_CADASTRAIS_DEST(
ID INT PRIMARY KEY NOT NULL,
CNPJ_CPF CHAR(14),
IE CHAR(14),
RAZAO_SOCIAL CHAR(35),
LOGRADOURO CHAR(45),
NUMERO CHAR(5),
COMPLEMENTO CHAR(15),
CEP CHAR(8),
BAIRRO CHAR(15),
MUNICIPIO CHAR(30),
UF CHAR(2),
TEL_CONTATO CHAR(10),
COD_IDENT_CONSUMIDOR CHAR(12),
NUM_TERMINAL CHAR(10),
UF_TERMINAL CHAR(2)

);