# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc714ce2738054d4692ffe4edda91e422fc2e53a8a775cd5ab57803f1e8b0e3485107ed20c3350991ef41068c559d4d1b910971ab56356d628cc317961003063

test:
  secret_key_base: 371dddcbafe8f31f6edeb260018bc4da46c863ecb8ddc6ae0bd9dbad1ea60cdabffb7caff0113a6ad976d856536023971e4f8ec77db50e8374caf8beb9228a22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
